from transactions.models import Container, User

DEFAULT_USERS = [
    {
        "username": "admin",
        "password": "password",
        "first_name": "System",
        "last_name": "Administrator",
        "superuser": True,
        "staff": True,
    },
    {
        "username": "researcher",
        "password": "password",
        "first_name": "A",
        "last_name": "Researcher",
        "superuser": False,
        "staff": False,
    }
]

DEFAULT_CONTAINERS = [
    {
        "title": "Rockefeller Foundation records: RG1.1: Box 34",
        "building": "Rockefeller Archive Center",
        "room": "104",
        "range": "4",
        "shelf": "2",
        "box_number": "34",
        "barcode": "A00000000000000001",
        "height": 10.5,
        "width": 5,
        "depth": 12.5,
    },
    {
        "title": "Rockefeller Foundation records: RG1.1: Box 35",
        "building": "Rockefeller Archive Center",
        "room": "104",
        "range": "4",
        "shelf": "2",
        "box_number": "35",
        "barcode": "A00000000000000002",
        "height": 10.5,
        "width": 5,
        "depth": 12.5,
    },
    {
        "title": "Rockefeller Foundation records: RG1.1: Box 78",
        "building": "Rockefeller Archive Center",
        "room": "104",
        "range": "4",
        "shelf": "5",
        "box_number": "78",
        "barcode": "A00000000000000035",
        "height": 10.5,
        "width": 5,
        "depth": 12.5,
    },
    {
        "title": "Rockefeller Foundation records: RG1.1: Box 82",
        "building": "Rockefeller Archive Center",
        "room": "104",
        "range": "4",
        "shelf": "7",
        "box_number": "82",
        "barcode": "A00000000000000055",
        "height": 10.5,
        "width": 5,
        "depth": 12.5,
    },
    {
        "title": "Ford Foundation records, Department of Important affairs: Box 12",
        "building": "Rockefeller Archive Center",
        "room": "206",
        "range": "8",
        "shelf": "2",
        "box_number": "12",
        "barcode": "A00000000000000355",
        "height": 10.5,
        "width": 5,
        "depth": 12.5,
    },
    {
        "title": "Ford Foundation records, Department of Important affairs: Box 89",
        "building": "Rockefeller Archive Center",
        "room": "206",
        "range": "3",
        "shelf": "2",
        "box_number": "89",
        "barcode": "A00000000000000255",
        "height": 10.5,
        "width": 5,
        "depth": 12.5,
    },
    {
        "title": "Ford Foundation records, Department of Important affairs: Box 106",
        "building": "Rockefeller Archive Center",
        "room": "206",
        "range": "5",
        "shelf": "2",
        "box_number": "106",
        "barcode": "A00000000000000455",
        "height": 10.5,
        "width": 5,
        "depth": 12.5,
    },
    {
        "title": "Village Green Preservation Society records: Photographs: Album 3",
        "building": "Rockefeller Archive Center",
        "room": "106",
        "range": "10",
        "shelf": "2",
        "box_number": "3",
        "barcode": "A00000000000001455",
        "height": 10.5,
        "width": 5,
        "depth": 12.5,
    },
    {
        "title": "Village Green Preservation Society records: Photographs: Album 4",
        "building": "Rockefeller Archive Center",
        "room": "106",
        "range": "10",
        "shelf": "2",
        "box_number": "4",
        "barcode": "A00000000000002455",
        "height": 10.5,
        "width": 5,
        "depth": 12.5,
    },
    {
        "title": "Village Green Preservation Society records: Recordings: Reel 3445",
        "building": "Rockefeller Archive Center",
        "room": "106",
        "range": "2",
        "shelf": "2",
        "box_number": "4",
        "barcode": "A00000000000003455",
        "height": 10.5,
        "width": 5,
        "depth": 12.5,
    },
    {
        "title": "Village Green Preservation Society records: Recordings: Album 3465",
        "building": "Rockefeller Archive Center",
        "room": "106",
        "range": "2",
        "shelf": "2",
        "box_number": "4",
        "barcode": "A00000000000004455",
        "height": 10.5,
        "width": 5,
        "depth": 12.5,
    },
    {
        "title": "Charitable Foundation records: Department of Important Affairs: Box 1282",
        "building": "Rockefeller Archive Center",
        "room": "302",
        "range": "2",
        "shelf": "2",
        "box_number": "1282",
        "barcode": "A00000000000004455",
        "height": 10.75,
        "width": 13,
        "depth": 16.25,
    },
    {
        "title": "Charitable Foundation records: Department of Important Affairs: Box 1283",
        "building": "Rockefeller Archive Center",
        "room": "302",
        "range": "2",
        "shelf": "1",
        "box_number": "1283",
        "barcode": "A00000000000004455",
        "height": 10.75,
        "width": 13,
        "depth": 16.25,
    },
    {
        "title": "Charitable Foundation records: Department of Important Affairs: Box 1284",
        "building": "Rockefeller Archive Center",
        "room": "302",
        "range": "5",
        "shelf": "8",
        "box_number": "1284",
        "barcode": "A00000000000004455",
        "height": 10.75,
        "width": 13,
        "depth": 16.25,
    },
    {
        "title": "Charitable Foundation records: Department of Important Affairs: Box 1285",
        "building": "Rockefeller Archive Center",
        "room": "302",
        "range": "8",
        "shelf": "1",
        "box_number": "1285",
        "barcode": "A00000000000004455",
        "height": 10.75,
        "width": 13,
        "depth": 16.25,
    },
    {
        "title": "Charitable Foundation records: Department of Important Affairs: Box 1286",
        "building": "Rockefeller Archive Center",
        "room": "302",
        "range": "9",
        "shelf": "6",
        "box_number": "1286",
        "barcode": "A00000000000004455",
        "height": 10.75,
        "width": 13,
        "depth": 16.25,
    },
    {
        "title": "Charitable Foundation records: Department of Important Affairs: Box 1288",
        "building": "Rockefeller Archive Center",
        "room": "302",
        "range": "1",
        "shelf": "6",
        "box_number": "1288",
        "barcode": "A00000000000004455",
        "height": 10.75,
        "width": 13,
        "depth": 16.25,
    }

]

if not len(User.objects.all()):
    for user in DEFAULT_USERS:
        new_user = User.objects.create_user(
            user['username'],
            first_name=user['first_name'],
            last_name=user['last_name'],
            email="{}@example.org".format(user['username']),
            is_superuser=user['superuser'],
            is_staff=user['staff'])
        new_user.set_password(user['password'])
        new_user.save()

if not len(Container.objects.all()):
    for container in DEFAULT_CONTAINERS:
        new_container = Container.objects.create(
            title=container['title'],
            location_building=container['building'],
            location_room=container['room'],
            location_range=container['range'],
            location_shelf=container['shelf'],
            box_number=container['box_number'],
            barcode=container['barcode'],
            height=container['height'],
            width=container['width'],
            depth=container['depth'],
        )
